name: Add a star to SWEET-Cat
description: Add a new planet-hosting star to the SWEET-Cat catalogue
title: "Add [star] to the catalogue"
labels: ["addition"]
assignees:
  - j-faria
body:
  - type: markdown
    attributes:
      value: |
        Here's a new planet-host star to be added to SWEET-Cat
  - type: input
    id: star_name
    attributes:
      label: Star Name
      description: What is the name (identifier) of the star?
      placeholder: ex. HD12345
    validations:
      required: true

  - type: checkboxes
    id: todo
    attributes:
      label: ToDo
      description: |
        The following steps are necessary to add a star to SWEET-Cat. Please check the completed ones
      options:
        - label: This star is a planet host
          required: true
        - label: The planet(s) were detected with the Radial Velocity or Transit methods
          required: true
